services:
  - name: eden-snake-game
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
    autoDeploy: true